const dummyText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Facilisi etiam dignissim diam quis. Ultricies mi eget mauris pharetra et ultrices neque ornare aenean. Amet justo donec enim diam vulputate ut pharetra sit. Consequat semper viverra nam libero justo laoreet sit amet. Leo vel fringilla est ullamcorper eget nulla facilisi. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Turpis tincidunt id aliquet risus. Cras ornare arcu dui vivamus arcu felis. Massa massa ultricies mi quis hendrerit dolor magna eget. Suspendisse interdum consectetur libero id faucibus. Senectus et netus et malesuada fames ac turpis egestas. Ac orci phasellus egestas tellus rutrum tellus.\n" +
    "\n" +
    "Dignissim sodales ut eu sem integer vitae justo eget. Penatibus et magnis dis parturient. Habitant morbi tristique senectus et netus et. Curabitur vitae nunc sed velit dignissim. Lectus urna duis convallis convallis tellus id. At elementum eu facilisis sed odio morbi. Faucibus pulvinar elementum integer enim. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Quam adipiscing vitae proin sagittis nisl. Nulla aliquet enim tortor at auctor urna. Nisl pretium fusce id velit ut. Egestas congue quisque egestas diam. Quisque sagittis purus sit amet volutpat consequat mauris nunc.\n" +
    "\n" +
    "In iaculis nunc sed augue lacus viverra vitae congue eu. Proin sed libero enim sed faucibus turpis in eu mi. Ut consequat semper viverra nam libero justo laoreet sit. Sodales neque sodales ut etiam sit amet nisl purus in. Duis at tellus at urna condimentum. Suspendisse ultrices gravida dictum fusce ut placerat. Arcu dictum varius duis at consectetur lorem. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Eget gravida cum sociis natoque penatibus et magnis. Risus commodo viverra maecenas accumsan lacus vel. Adipiscing vitae proin sagittis nisl.\n" +
    "\n" +
    "In est ante in nibh mauris cursus mattis molestie. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Mattis vulputate enim nulla aliquet porttitor lacus. Neque egestas congue quisque egestas. Convallis tellus id interdum velit. Arcu cursus euismod quis viverra nibh cras pulvinar mattis. Interdum consectetur libero id faucibus nisl tincidunt eget nullam non. Sapien eget mi proin sed libero enim sed faucibus. Id neque aliquam vestibulum morbi. Ipsum dolor sit amet consectetur adipiscing. Vitae nunc sed velit dignissim sodales ut eu sem integer. Viverra orci sagittis eu volutpat odio. Pharetra convallis posuere morbi leo urna molestie at. Quam vulputate dignissim suspendisse in est ante in nibh. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque.\n" +
    "\n" +
    "In egestas erat imperdiet sed. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Vitae purus faucibus ornare suspendisse sed nisi lacus sed. Varius quam quisque id diam vel quam elementum pulvinar etiam. Hendrerit gravida rutrum quisque non tellus orci. Vestibulum sed arcu non odio euismod lacinia at. Amet consectetur adipiscing elit ut aliquam purus sit amet. Libero nunc consequat interdum varius sit amet. Amet tellus cras adipiscing enim. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Sit amet nulla facilisi morbi. Ultrices neque ornare aenean euismod elementum nisi. At augue eget arcu dictum varius duis. Vel eros donec ac odio tempor orci dapibus ultrices. Dictumst quisque sagittis purus sit amet volutpat consequat. A diam maecenas sed enim ut sem. Eu ultrices vitae auctor eu augue ut. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Commodo ullamcorper a lacus vestibulum sed arcu non."

export default dummyText